package com.redhat.demo.qlb.loan_application.rules;

import com.redhat.demo.qlb.loan_application.model.Applicant ;
import com.redhat.demo.qlb.loan_application.model.Loan;

rule "Setting default values on Applicant"
	ruleflow-group "initialisation-rules"
	no-loop true
	when
	    applicant : Applicant( )
	then
	    System.out.println("Rule fired : [" + drools.getRule().getName()+"]");
	    applicant.setEligible( true );
	    applicant.setMonthlyIncome (applicant.getYearlyIncome()/12);
end

rule "Setting default values on Loan"
	ruleflow-group "initialisation-rules"
	no-loop true
	when
	    loan : Loan( )
	then
	    System.out.println("Rule fired : [" + drools.getRule().getName()+"]");
	    loan.setApproved( false );
end